### ISSUE TITLE
Upload to luarocks

### ISSUE THREAD

**Issue by drolando** [spacewander/lua-resty-murmurhash3#1]
Can you upload it to luarocks?

**Comment by spacewander** [comment]
@drolando 
I will try to do it once I have free time.

**Comment by spacewander** [comment]
Already added it to my weekend schedule.

**Comment by spacewander** [comment]
@drolando 
I have already upload it to luarocks.
Now you could install it via `luarocks install lua-resty-murmurhash3`.
Note that `cmake` and `luajit` are required, though I could not add them into dependencies section of the rockspec.
